.TH STERMCOM "1" "December 2015"
.SH NAME
stermcom \- terminal emulator
.SH SYNOPSIS
.B stermcom
[\fB-h\fR] [\fB-b\fR \fIBAUDRATE\fR] \fIDEVICENODE\fR
.SH DESCRIPTION
.PP
This is a simple terminal emulator.
.SH OPTIONS
.TP
\fB-h\fR
Use external history.
.TP
\fB-b\fR
Set the baud rate.
.SH AUTHOR
Written by Yoshinori Sugino.
.SH COPYRIGHT
The MIT License (MIT)
.br
Copyright \(co 2015 Yoshinori Sugino
